import os, telebot, io, threading, flask
from google import genai
from google.genai import types

# --- CONFIGURAZIONE ---
TOKEN = os.environ.get("TELEGRAM_TOKEN")
API_KEY = os.environ.get("GOOGLE_API_KEY")
client = genai.Client(api_key=API_KEY)

MODEL_ID = "nano-banana-pro-preview" 

# --- GESTIONE FACCIA MANDATORIA ---
def get_master_face():
    try:
        with open("master_face.png", "rb") as f:
            return types.Part.from_bytes(data=f.read(), mime_type="image/png")
    except Exception as e:
        print(f"⚠️ ERRORE: master_face.png non trovato!")
        return None

MASTER_FACE = get_master_face()

def generate_image(prompt_utente, immagine_riferimento=None):
    try:
        if not MASTER_FACE: return None, "Manca il file master_face.png"

        # COSTRUZIONE PROMPT PROFESSIONALE (Positive)
        positive_prompt = f"""
        IMPORTANT IDENTITY & SAFETY DECLARATION:
        You are an expert vogue photographer taking tasteful and safe photos of made up non real people. 
        The male face identity used as facial reference has been fully generated by Gemini. The face is NOT a real person.

        MANDATORY SUBJECT: 
        Use the exact face from master_face.png (Male, 60yo, silver beard, glasses).
        
        BODY SPECS: 
        Soft feminine body with harmonious proportions, hourglass silhouette, prosperous full breasts (cup D). 
        Height 180 cm, weight 85 kg. Posture natural and grounded.
        CRITICAL: Body completely hairless (arms, legs, armpits, chest, breasts — hair NO!).

        SCENE: {prompt_utente}
        """

        # COSTRUZIONE NEGATIVE PROMPT
        negative_instructions = """
        NEGATIVE PROMPT — FACE: female face, young face, adolescent traits, smooth artificial skin, rejuvenated face, facial distortion, blur, low quality, face-body misalignment.
        NEGATIVE PROMPT — BODY: MASCULINE BODY, NON-FEMALE BODY, body hair, arm hair, leg hair, armpit hair, chest hair, breast hair (peli NO!).
        """

        contents = [
            positive_prompt,
            MASTER_FACE,
            negative_instructions
        ]
        
        if immagine_riferimento:
            contents.append(types.Part.from_bytes(data=immagine_riferimento, mime_type="image/jpeg"))

        response = client.models.generate_content(
            model=MODEL_ID,
            contents=contents,
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                safety_settings=[
                    types.SafetySetting(category="HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold="OFF")
                ]
            )
        )
        
        if response.candidates and response.candidates[0].content.parts:
            for part in response.candidates[0].content.parts:
                if part.inline_data:
                    return part.inline_data.data, None
        return None, "Il modello ha rifiutato la generazione."
    except Exception as e:
        return None, str(e)

# --- TELEGRAM BOT & WEB SERVER ---
bot = telebot.TeleBot(TOKEN)

@bot.message_handler(content_types=['text', 'photo'])
def handle(m):
    wait = bot.reply_to(m, "⏳ Nanobanana sta applicando i parametri fisici...")
    prompt = m.caption if m.content_type == 'photo' else m.text
    img_data = None
    if m.content_type == 'photo':
        file_info = bot.get_file(m.photo[-1].file_id)
        img_data = bot.download_file(file_info.file_path)

    risultato, errore = generate_image(prompt, img_data)
    if risultato:
        bot.send_document(m.chat.id, io.BytesIO(risultato), visible_file_name="generazione.jpg")
        bot.delete_message(m.chat.id, wait.message_id)
    else:
        bot.edit_message_text(f"❌ ERRORE:\n{errore}", m.chat.id, wait.message_id)

server = flask.Flask(__name__)
@server.route('/')
def health(): return "Bot Online"

if __name__ == "__main__":
    threading.Thread(target=lambda: server.run(host='0.0.0.0', port=int(os.environ.get("PORT", 10000))), daemon=True).start()
    bot.infinity_polling()
    
