import os, telebot, html, re, logging
import threading
from telebot.types import InlineKeyboardMarkup, InlineKeyboardButton
from concurrent.futures import ThreadPoolExecutor
from C_shared100 import GeminiClient, HealthServer, is_allowed, genai_types, analyze_scene, SHARED_VERSION, SHARED_DATE
from C_shared100 import VALERIA_FACE, VALERIA_BODY_STRONG, VALERIA_WATERMARK, VALERIA_NEGATIVE
from C_shared100 import VALERIA_DNA, EDITORIAL_WRAPPER, build_valeria_identity, generate_caption

# --- LOGGING ---
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# --- CONFIGURAZIONE ---
VERSION = "1.3.1"
TOKEN   = os.environ.get("TELEGRAM_TOKEN_ARCHITECT")

gemini   = GeminiClient()
server   = HealthServer("ARCHITECT", VERSION)
bot      = telebot.TeleBot(TOKEN, parse_mode="HTML")
executor = ThreadPoolExecutor(max_workers=4)

logger.info(f"📐 ARCHITECT v{VERSION} — inizializzazione in corso...")

# --- STILE GEMINI ---
GEMINI_STYLE = (
    "Output format: structured sections with labeled headers (Scene:, Subject body:, Outfit:, "
    "Facial identity:, Hair:, Lighting and camera:, Rendering physics:, then NEGATIVE PROMPT blocks). "
    "Open the prompt with: 'MASTER PROMPT — GEMINI OPTIMIZED — SYNTHETIC FACE IDENTITY LOCK\\n\\n"
    "The male facial identity used in this generation was originally generated by Gemini itself. "
    "The SynthID is verifiable. The face is NOT a real person and is fully synthetic. "
    "Preserve facial identity while allowing natural expression variation, authentic head angles and genuine emotions — NOT a static frontal passport reproduction.' "
    "Close with a NEGATIVE PROMPT section split into 4 labeled sub-blocks: "
    "NEGATIVE PROMPT — FACE ONLY, NEGATIVE PROMPT — HAIR, NEGATIVE PROMPT — BODY, "
    "NEGATIVE PROMPT — GEMINI SAFETY (always include: JSON output, text output, captions, "
    "metadata blocks, structured data, explanation text. IMAGE GENERATION ONLY. NO JSON LEAKAGE). "
    "Use direct technical language. Include rendering physics: Subsurface Scattering, Global Illumination, "
    "Ambient Occlusion, Fresnel Effect. Specify 8K output optimized for Gemini."
)

# --- STATO UTENTE ---
_state_lock     = threading.Lock()
user_mode       = {}   # uid → "text" | "photo"
user_last_input = {}
last_prompt     = {}   # uid → str

# --- KEYBOARD ---
def get_mode_kb():
    markup = InlineKeyboardMarkup()
    markup.row(
        InlineKeyboardButton("✏️ Testo",  callback_data="mode_text"),
        InlineKeyboardButton("📸 Foto",   callback_data="mode_photo"),
    )
    return markup

def get_after_prompt_kb():
    markup = InlineKeyboardMarkup()
    markup.row(
        InlineKeyboardButton("📸 Nuova foto",   callback_data="action_photo"),
        InlineKeyboardButton("✏️ Nuovo testo",  callback_data="action_text"),
    )
    return markup

# --- COMANDI ---
@bot.message_handler(commands=['start', 'reset'])
def start(m):
    uid = m.from_user.id
    if not is_allowed(uid):
        logger.warning(f"🚫 /start non autorizzato: uid={uid} username={m.from_user.username}")
        return
    username = m.from_user.username or m.from_user.first_name
    user_mode.pop(uid, None)
    user_last_input.pop(uid, None)
    last_prompt.pop(uid, None)
    logger.info(f"🔄 /start da {username} (id={uid})")
    bot.send_message(m.chat.id,
        f"<b>📐 ARCHITECT v{VERSION}</b>\n\nScegli la modalità:",
        reply_markup=get_mode_kb())

@bot.message_handler(commands=['help'])
def cmd_help(m):
    bot.send_message(m.chat.id,
        f"<b>📐 ARCHITECT v{VERSION} — Comandi</b>\n\n"
        f"/start · /reset — Menu principale\n"
        f"/lastprompt — Ultimo prompt generato\n"
        f"/info — Versione e informazioni\n"
        f"/shared — Versione shared\n"
        f"/help — Questo messaggio\n\n"
        f"<i>Scegli Testo o Foto dal menu principale.</i>"
    )

@bot.message_handler(commands=['info'])
def cmd_info(m):
    uid = m.from_user.id
    mode = user_mode.get(uid, "Non selezionata")
    bot.send_message(m.chat.id,
        f"<b>📐 ARCHITECT v{VERSION}</b>\n\n"
        f"Modalità attiva: <b>{mode}</b>\n"
        f"Motore: <code>gemini-3-flash-preview</code> (Flow)\n\n"
        f"<i>Output: prompt Flow-ready + caption.</i>"
    )

@bot.message_handler(commands=['lastprompt'])
def cmd_lastprompt(m):
    uid = m.from_user.id
    username = m.from_user.username or m.from_user.first_name
    logger.info(f"🔍 /lastprompt da {username} (id={uid})")
    prompt = last_prompt.get(uid)
    if not prompt:
        bot.send_message(m.chat.id, "⚠️ Nessun prompt disponibile. Genera prima un prompt.")
        return
    chunks = [prompt[i:i+3800] for i in range(0, len(prompt), 3800)]
    for idx, chunk in enumerate(chunks):
        header = f"🔍 <b>Ultimo prompt generato</b> ({idx+1}/{len(chunks)}):\n\n" if idx == 0 else f"<i>(continua {idx+1}/{len(chunks)})</i>\n\n"
        bot.send_message(m.chat.id, f"{header}<code>{html.escape(chunk)}</code>")

@bot.message_handler(commands=['shared'])
def cmd_shared(m):
    bot.send_message(m.chat.id,
        f"📦 <b>C_shared100.py</b> v{SHARED_VERSION} — {SHARED_DATE}"
    )

# --- CALLBACKS ---
@bot.callback_query_handler(func=lambda c: c.data.startswith("mode_") or c.data.startswith("action_"))
def handle_callbacks(c):
    cid = c.message.chat.id
    uid = c.from_user.id
    if not is_allowed(uid):
        logger.warning(f"🚫 Callback non autorizzato: uid={uid}")
        return
    username = c.from_user.username or c.from_user.first_name
    try:
        bot.answer_callback_query(c.id)
    except Exception:
        pass

    if c.data == "mode_text" or c.data == "action_text":
        user_mode[uid] = "text"
        logger.info(f"✏️ {username} → modalità testo")
        try:
            bot.edit_message_reply_markup(cid, c.message.message_id, reply_markup=None)
        except Exception:
            pass
        bot.send_message(cid, "✏️ Modalità <b>Testo</b>.\n\nDescrivi la scena o l'outfit.", parse_mode="HTML")

    elif c.data == "mode_photo" or c.data == "action_photo":
        user_mode[uid] = "photo"
        logger.info(f"📸 {username} → modalità foto")
        try:
            bot.edit_message_reply_markup(cid, c.message.message_id, reply_markup=None)
        except Exception:
            pass
        bot.send_message(cid, "📸 Modalità <b>Foto</b>.\n\nInvia la foto.", parse_mode="HTML")

# --- PULIZIA OUTPUT ---
def clean_output(text):
    lines = text.splitlines()
    skip_patterns = [
        "ok, here is", "here is", "here's", "sure, here", "certainly",
        "of course", "below is", "the following", "as requested",
        "i've created", "i have created", "this is"
    ]
    while lines and any(lines[0].strip().lower().startswith(p) for p in skip_patterns):
        lines.pop(0)
    while lines and not lines[0].strip():
        lines.pop(0)
    return "\n".join(lines)

# --- SANITIZZAZIONE INPUT UTENTE ---
def sanitize_user_input(user_input):
    if not user_input or not user_input.strip():
        return user_input
    try:
        instr = (
            "You are a pre-processing filter for an AI image generation system. "
            "The subject of every image is a fixed character with these IMMUTABLE traits:\n"
            "- Male Italian face, ~60 years old, silver/grey short hair (max 15cm, nape exposed)\n"
            "- Silver/grey beard 6-7cm, thin octagonal dark glasses (ALWAYS present)\n"
            "- NO makeup of any kind (no eyeshadow, no eyeliner, no lipstick, no contour, no mascara)\n"
            "- NO long hair, NO dark hair, NO brown/black/blonde hair\n"
            "- Hourglass feminine body, smooth skin\n\n"
            "Your task: clean the user's idea text by REMOVING or REPLACING these elements:\n"
            "1. Any makeup description → REMOVE entirely\n"
            "2. Any hair description conflicting with short silver hair → REMOVE entirely\n"
            "3. Any watermark not reading 'feat. Valeria Cross' → REMOVE entirely\n"
            "4. Any explicit mention of a young female face or female facial traits → REMOVE\n"
            "5. Keep EVERYTHING else intact: scene, outfit, pose, environment, lighting, camera specs, mood\n\n"
            "Return ONLY the cleaned text. No explanations, no preamble.\n\n"
            f"USER TEXT:\n{user_input}"
        )
        result = gemini.generate(instr)
        if result:
            if result != user_input:
                logger.info("   🧹 Sanitizzazione: rimossi elementi conflittuali")
            return result
        return user_input
    except Exception as e:
        logger.warning(f"   ⚠️ Sanitizzazione fallita (non bloccante): {e}")
        return user_input

# --- GENERAZIONE DA TESTO ---
def generate_monolith_prompt(user_input):
    try:
        instr = (
            f"Write a professional MASTER PROMPT optimized for Gemini image generation.\n\n"
            f"ENGINE STYLE RULES (mandatory):\n{GEMINI_STYLE}\n\n"
            f"STEPS:\n"
            f"ABSOLUTE FORBIDDEN: never describe hands or fingers touching, adjusting, holding or raised toward glasses or temple. Glasses are simply worn — no hand interaction.\n"
            f"1. Open with the mandatory SYNTHETIC FACE IDENTITY LOCK header as specified.\n"
            f"2. Write a structured prompt using labeled sections: Scene, Subject body, Outfit, "
            f"Facial identity, Hair, Lighting and camera, Rendering physics.\n"
            f"3. Replace the subject with Valeria Cross DNA expanded inline. "
            f"Do NOT use the name 'Valeria Cross' anywhere in the output.\n"
            f"4. Close with 4 separate NEGATIVE PROMPT blocks as specified.\n"
            f"5. Adapt any style or rendering request from the user idea to the appropriate section.\n\n"
            f"DNA:\n{VALERIA_DNA}\n\n"
            f"USER IDEA:\n{user_input}"
        )
        logger.info("   📤 Chiamata API testo...")
        result = gemini.generate(instr)
        if result:
            logger.info(f"   ✅ Risposta ricevuta ({len(result)} chars)")
            return result
        logger.warning("   ⚠️ Risposta API vuota.")
        return "⚠️ Risposta vuota."
    except Exception as e:
        logger.error(f"   ❌ Errore API testo: {e}", exc_info=True)
        return f"ERRORE API: {str(e)}"

# --- GENERAZIONE DA IMMAGINE ---
def generate_from_image(img_bytes, extra_text):
    try:
        vs_context = ""
        if extra_text:
            vs_context = (
                f"\nSTRUCTURED IMAGE ANALYSIS (use as primary reference for scene, "
                f"lighting, outfit, composition, colors, micro-details):\n{extra_text}\n\n"
            )

        instr = (
            f"You are given a reference image. Your task has TWO mandatory phases:\n\n"
            f"PHASE 1 — SCENE EXTRACTION (internal only, do NOT output this phase):\n"
            f"Look carefully at the image and extract the key visual details mentally:\n"
            f"- Environment/location: indoor/outdoor, specific setting, architecture, props\n"
            f"- Outfit: garments, fabric type, color (HEX), cut, fit, embellishments, shoes\n"
            f"- Lighting: natural/artificial, direction, color temperature, mood\n"
            f"- Pose: body position, camera angle, framing\n"
            f"- Background: textures, colors, elements\n"
            f"Do NOT output Phase 1. It is internal preparation only.\n\n"
            f"PHASE 2 — PROMPT GENERATION (this is the ONLY output):\n"
            f"Write a concise MASTER PROMPT for Gemini image generation.\n"
            f"Replace the original subject with the DNA below. Keep the scene faithful to the reference.\n\n"
            f"CONCISENESS RULES (mandatory):\n"
            f"- Scene section: 3-4 lines maximum. Location + atmosphere + lighting mood.\n"
            f"- Outfit section: be detailed and precise — fabric, color HEX, cut, every embellishment.\n"
            f"- All other sections: as detailed as needed for accurate generation.\n"
            f"- Do NOT dump raw image analysis text into any section. Write prompts, not descriptions.\n\n"
            f"ENGINE STYLE RULES (mandatory):\n{GEMINI_STYLE}\n\n"
            f"{vs_context}"
            f"STEPS:\n"
            f"ABSOLUTE FORBIDDEN: never describe hands or fingers touching, adjusting, holding or raised toward glasses or temple. Glasses are simply worn — no hand interaction.\n"
            f"1. Open with the mandatory SYNTHETIC FACE IDENTITY LOCK header as specified.\n"
            f"2. Write a structured prompt using labeled sections: Scene, Subject body, Outfit, "
            f"Facial identity, Hair, Lighting and camera, Rendering physics.\n"
            f"3. The Scene section MUST faithfully describe the real location/environment from the image — "
            f"NEVER use generic descriptions like 'studio' unless the reference actually shows a studio. "
            f"Replace the original subject entirely with DNA expanded inline. "
            f"Do NOT use the name 'Valeria Cross' anywhere in the output.\n"
            f"4. Close with 4 separate NEGATIVE PROMPT blocks as specified.\n\n"
            f"DNA:\n{VALERIA_DNA}\n\n"
        )

        from C_shared100 import detect_mime_type
        mime = detect_mime_type(img_bytes)
        img_part = genai_types.Part.from_bytes(data=img_bytes, mime_type=mime)
        logger.info(f"   📤 Chiamata API immagine (mime={mime})...")
        response_text = gemini.generate(instr, contents=[img_part])
        if response_text:
            logger.info(f"   ✅ Risposta ricevuta ({len(response_text)} chars)")
            return response_text.strip()

        # Fallback senza immagine
        logger.warning("   ⚠️ Risposta vuota con immagine — fallback senza immagine.")
        fallback_context = (
            f"The reference image could not be analyzed directly. "
            f"Use these extra instructions as outfit/scene context:\n{extra_text}\n\n"
            if extra_text else
            "No image analysis available. Generate a prompt based on DNA only.\n\n"
        )
        instr_fallback = instr.replace(
            f"ENGINE STYLE RULES (mandatory):\n{GEMINI_STYLE}\n\n",
            f"ENGINE STYLE RULES (mandatory):\n{GEMINI_STYLE}\n\n{fallback_context}"
        )
        response_text2 = gemini.generate(instr_fallback)
        if response_text2:
            logger.info(f"   ✅ Risposta fallback ({len(response_text2)} chars)")
            return response_text2.strip()

        logger.warning("   ⚠️ Risposta vuota anche in fallback.")
        return "⚠️ Risposta vuota."
    except Exception as e:
        logger.error(f"   ❌ Errore API immagine: {e}", exc_info=True)
        return f"ERRORE API: {str(e)}"

# --- REVIEW E FIX CONTRADDIZIONI ---
def review_and_fix(prompt):
    try:
        review_instr = (
            f"You are a prompt quality reviewer. Carefully read the following image generation prompt "
            f"and fix ALL contradictions, inconsistencies and conflicts. Return ONLY the corrected prompt, "
            f"no explanations, no preamble.\n\n"
            f"MANDATORY FIXES — apply all of these:\n\n"
            f"1. HAIR: Valeria Cross has SHORT silver/grey hair (sides 1-2cm, top max 15cm, nape exposed). "
            f"Remove or replace ANY mention of: long hair, brown hair, dark hair, black hair, curly hair, "
            f"flowing hair, loose waves, slicked back long hair, wet long hair, hair falling on shoulders, "
            f"hair spread around head, hair fanned out, dark flowing locks, wavy dark hair, hair against background. "
            f"Replace with: short silver Italian cut, slightly voluminous top, nape exposed.\n\n"
            f"2. GLASSES MANDATORY: Valeria Cross ALWAYS wears thin octagonal Vogue Havana dark tortoiseshell glasses. "
            f"If the prompt does NOT mention glasses or eyeglasses, ADD this phrase in the Facial identity section: "
            f"'thin octagonal Vogue Havana dark tortoiseshell frame eyeglasses (MANDATORY, always present)'. "
            f"Also ensure 'no glasses' does NOT appear anywhere in the prompt.\n\n"
            f"2b. GLASSES POSE REMOVAL: Remove ANY description of hands or fingers touching, adjusting, holding or "
            f"raising to the glasses or temple area. The glasses are simply worn — no hand interaction with them.\n\n"
            f"3. NEGATIVE PROMPTS CONFLICTS: Scan the negative prompts section. "
            f"Remove from negatives any term that contradicts a positive element in the prompt.\n\n"
            f"3b. MIRROR SELFIE RULE: If the prompt contains selfie, mirror, mirror selfie, bathroom, restroom, reflection — "
            f"smartphone held in hand IS a required prop. Ensure it is present as positive element and removed from negatives.\n\n"
            f"4. SUBJECT BLEED: Remove any physical description belonging to the original reference subject. "
            f"Valeria Cross DNA: Male Italian face 60yo, silver beard 6-7cm, octagonal Vogue glasses, "
            f"silver short hair, hourglass body, smooth skin.\n\n"
            f"5. WATERMARK TEXT: Must read exactly: 'feat. Valeria Cross 👠' "
            f"in elegant champagne cursive, very small, bottom center/left, 90% opacity. "
            f"Replace any other watermark text with the exact text above.\n\n"
            f"6. NAME REMOVAL: Remove any occurrence of 'Valeria Cross' or 'DNA of Valeria Cross' from the prompt body.\n\n"
            f"7. KEEP INTACT: scene, outfit, lighting, environment, pose, mood, camera settings, "
            f"photographic style, watermark spec, all creative elements not related to the subject's identity.\n\n"
            f"8. BODY HAIR ENFORCEMENT: Ensure Subject body section explicitly states: "
            f"'completely hairless body', 'no body hair, no chest hair, no arm hair, no leg hair', "
            f"'soft feminine hourglass silhouette'. "
            f"In NEGATIVE PROMPT — BODY ensure: 'body hair, chest hair, arm hair, leg hair, hairy torso, hairy arms'.\n\n"
            f"PROMPT TO REVIEW:\n\n{prompt}"
        )
        logger.info("   🔍 Review contraddizioni...")
        response = gemini._client.models.generate_content(
            model=gemini._model,
            contents=review_instr,
            config=genai_types.GenerateContentConfig(
                temperature=0.3,
                max_output_tokens=8192,
            )
        )
        if response and response.text:
            fixed = response.text.strip()
            logger.info(f"   ✅ Review completata ({len(fixed)} chars)")
            return fixed
        logger.warning("   ⚠️ Review: risposta vuota, uso prompt originale.")
        return prompt
    except Exception as e:
        logger.warning(f"   ⚠️ Review fallita, uso prompt originale: {e}")
        return prompt

# --- INVIO PROMPT ---
def send_prompt(cid, uid, certified, img_bytes=None):
    """Invia il prompt certificato in chunks con pulsanti post-prompt e caption automatica."""
    with _state_lock:
        last_prompt[uid] = certified
    ARCH_TAG = "[MASTER PROMPT — ARCHITECT CERTIFIED — SKIP OPTIMIZATION]"
    output = f"{ARCH_TAG}\n{certified}"
    chunks = [output[i:i+3800] for i in range(0, len(output), 3800)]
    for idx, chunk in enumerate(chunks):
        header = f"✅ <b>Master Prompt — Architect:</b>\n\n" if idx == 0 else f"<i>(continua {idx+1}/{len(chunks)})</i>\n\n"
        if idx == len(chunks) - 1:
            bot.send_message(cid, f"{header}<code>{html.escape(chunk)}</code>",
                reply_markup=get_after_prompt_kb())
        else:
            bot.send_message(cid, f"{header}<code>{html.escape(chunk)}</code>")
    if img_bytes:
        cap, _ = generate_caption(img_bytes, gemini)
        if cap:
            bot.send_message(cid, cap, parse_mode=None)

# --- HANDLER TESTO ---
@bot.message_handler(content_types=['text'])
def handle_text(m):
    if m.text and m.text.startswith('/'):
        return
    uid = m.from_user.id
    if not is_allowed(uid):
        logger.warning(f"🚫 Testo non autorizzato: uid={uid}")
        return
    if user_mode.get(uid) != "text":
        bot.send_message(m.chat.id,
            "Scegli prima la modalità:",
            reply_markup=get_mode_kb())
        return
    username = m.from_user.username or m.from_user.first_name
    logger.info(f"✏️ Testo da {username} (id={uid}): «{m.text[:60]}»")
    wait = bot.send_message(m.chat.id, "🚀 <b>Generazione in corso...</b>\n⏳ Attendi qualche secondo.")

    def task():
        try:
            sanitized = sanitize_user_input(m.text)
            raw = generate_monolith_prompt(sanitized)
            reviewed = review_and_fix(clean_output(raw))
            certified = clean_output(reviewed)
            try:
                bot.delete_message(m.chat.id, wait.message_id)
            except Exception:
                pass
            if "⚠️ Risposta vuota" in certified or "ERRORE API" in certified:
                bot.send_message(m.chat.id,
                    f"❌ <b>Generazione fallita.</b>\n\n<code>{html.escape(certified)}</code>",
                    reply_markup=get_mode_kb())
                return
            send_prompt(m.chat.id, uid, certified)
            logger.info(f"✅ Prompt testo inviato a {username} ({len(certified)} chars)")
        except Exception as e:
            logger.error(f"❌ task (testo) crash: {e}", exc_info=True)
            try:
                bot.delete_message(m.chat.id, wait.message_id)
            except Exception:
                pass
            bot.send_message(m.chat.id, f"❌ Errore generazione:\n<code>{html.escape(str(e))}</code>")

    executor.submit(task)

# --- HANDLER FOTO ---
@bot.message_handler(content_types=['photo'])
def handle_photo(m):
    uid = m.from_user.id
    if not is_allowed(uid):
        logger.warning(f"🚫 Foto non autorizzata: uid={uid}")
        return
    if user_mode.get(uid) != "photo":
        bot.send_message(m.chat.id,
            "Scegli prima la modalità:",
            reply_markup=get_mode_kb())
        return
    username = m.from_user.username or m.from_user.first_name
    try:
        file_info = bot.get_file(m.photo[-1].file_id)
        img_bytes = bot.download_file(file_info.file_path)
        logger.info(f"🖼️ Foto da {username} (id={uid}), {len(img_bytes)} bytes")
    except Exception as e:
        bot.reply_to(m, f"❌ Errore download foto: {html.escape(str(e))}")
        return

    wait = bot.send_message(m.chat.id,
        "🔍 <b>Analisi immagine in corso...</b>\n⏳ Attendi ~20-30 secondi.")

    outfit_desc, analyze_err = analyze_scene(img_bytes, gemini)
    if analyze_err:
        logger.warning(f"   ⚠️ analyze_scene: {analyze_err}")

    def task_single():
        try:
            logger.info(f"   🖼️ task_single avviato")
            raw = generate_from_image(img_bytes, outfit_desc)
            logger.info(f"   📝 generate completato ({len(raw)} chars)")
            reviewed = review_and_fix(clean_output(raw))
            certified = clean_output(reviewed)
            try:
                bot.delete_message(m.chat.id, wait.message_id)
            except Exception:
                pass
            if "⚠️ Risposta vuota" in certified or "ERRORE API" in certified:
                bot.send_message(m.chat.id,
                    f"❌ <b>Generazione fallita.</b>\n\n<code>{html.escape(certified)}</code>",
                    reply_markup=get_mode_kb())
                return
            send_prompt(m.chat.id, uid, certified, img_bytes)
            logger.info(f"✅ Prompt foto inviato a {username} ({len(certified)} chars)")
        except Exception as e:
            logger.error(f"   ❌ task_single crash: {e}", exc_info=True)
            try:
                bot.delete_message(m.chat.id, wait.message_id)
            except Exception:
                pass
            bot.send_message(m.chat.id, f"❌ Errore generazione:\n<code>{html.escape(str(e))}</code>")

    executor.submit(task_single)

# --- MAIN ---
if __name__ == "__main__":
    import time
    logger.info(f"📐 Avvio ARCHITECT v{VERSION}")
    server.start()
    while True:
        try:
            bot.infinity_polling(timeout=30, long_polling_timeout=25)
        except Exception as e:
            err = str(e)
            if "409" in err or "Conflict" in err:
                logger.warning("⚠️ 409 Conflict — altra istanza attiva. Attendo 15s e riprovo...")
                time.sleep(15)
            else:
                logger.error(f"❌ Polling error: {e}")
                time.sleep(5)
